profiles/urls.py
from django.conf.urls import url
import views


app_name = "profiles"
urlpatterns = [
    url(r'^$', views.users, name="full_list"),
    url(r'users_lst/', views.UsersListView.as_view(), name='simple_lst'),
    url(r'details/(?P<pk>\d+)/', views.UserDetailView.as_view(), name='user_detail'),
    url(r'new/', views.UsersCreateView.as_view(), name='new'),
]

registration/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth import views as auth_views

import views  # import our custom sign in view to also ask for an email

urlpatterns = [
    url('accounts/', include('django.contrib.auth.urls')),
    url(r'^home/', views.home, name='home'),
    url(r'^admin/', admin.site.urls),
    url(r'^users/', include('profiles.urls')),
    url(r'^$', auth_views.login, name='login'),
    url(r'^register/', views.signup, name='register'),  # use our custom view
    url(r'^logout/', auth_views.logout, name='logout'),
]

profiles/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.db import models
from .validators import (validate_first_name, validate_last_name, validate_email, validate_timezone,
                         validate_city, validate_state, validate_country)


class Address(models.Model):
    """
    A class representing an address.
    """
    address = models.TextField(max_length=100, null=False, blank=False)

    def __unicode__(self):
        return self.address

    class Meta:
        verbose_name_plural = 'Addresses'


class Gender(models.Model):
    """
    A class representing a gender.
    """

    GENDER_OPTIONS = (
        ('Male', 'Male'),
        ('Female', 'Female'),
    )

    gender = models.CharField(
        max_length=6,
        choices=GENDER_OPTIONS,
        default='Male',
        null=True,
        blank=True,
    )

    def __unicode__(self):
        return self.gender

    class Meta:
        abstract = True


class Users(Gender):
    """
    User data model representation.
    """
    first_name = models.CharField(max_length=100, validators=[validate_first_name])
    last_name = models.CharField(max_length=100, validators=[validate_last_name])
    age = models.IntegerField(null=True, blank=True)
    email = models.CharField(max_length=100, null=True, blank=False, validators=[validate_email])
    address = models.ForeignKey(Address, on_delete=models.CASCADE, null=False, blank=False)
    city = models.CharField(max_length=50, null=True, blank=True, validators=[validate_city])
    state = models.CharField(max_length=50, null=True, blank=True, validators=[validate_state])
    country = models.CharField(max_length=50, null=True, blank=True, validators=[validate_country])
    zip_code = models.IntegerField(null=True, blank=True)
    phone_number = models.CharField(max_length=50, null=True, blank=True)
    active = models.BooleanField(null=False, blank=False)
    timezone = models.CharField(max_length=50, null=True, blank=True, validators=[validate_timezone])

    def clean(self):
        pass

    def __unicode__(self):
        return "{0} {1}".format(self.first_name, self.last_name)

    class Meta:
        verbose_name_plural = 'Users'


class Medias(models.Model):
    """
    Social media model.
    """
    id = models.IntegerField(primary_key=True)
    name = models.CharField(max_length=50)
    url = models.URLField()
    user_id = models.OneToOneField(Users, on_delete=models.CASCADE)

    def __unicode__(self):
        return self.name

    class Meta:
        verbose_name_plural = 'Medias'

profiles/forms.py
from .models import Users, Address
from django import forms
from django.shortcuts import render


class AddressForm(forms.ModelForm):
    """
    A simple form for Address class.
    """
    class Meta:
        model = Address
        fields = ['address']
        labels = {'address': 'Address'}


class UsersForm(forms.ModelForm):
    """
    A form for the Users model.
    """
    class Meta:
        model = Users

        fields = [
            "first_name",
            "last_name",
            "age",
            "gender",
            "email",
            "city",
            "state",
            "country",
            "zip_code",
            "phone_number",
            "active",
            "timezone",
        ]

        labels = {
           "first_name": "First Name",
           "last_name": "Last Name",
           "age": "Age",
           "gender": "Gender",
           "email": "Email",
           "city": "City",
           "state": "State",
           "country": "Country",
           "zip_code": "Zip Code",
           "phone_number": "Phone Number",
           "active": "Active",
           "timezone": "Time Zone",
        }

profiles/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.shortcuts import render, HttpResponseRedirect
from django.views.generic import TemplateView, DetailView, ListView, CreateView
from django.urls.base import reverse_lazy
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator

# Create your views here.
from .models import Users
from .forms import UsersForm, AddressForm


@login_required
def users(request):
    """
    List all the users stored in the database.
    """
    users_lst = Users.objects.all()
    return render(request, 'profiles/users.html', {'users_lst': users_lst})


# This is what the exercise asked for, however,
# I used the UsersListView(ListView) instead.
# If you want to use it, just UserListView by UsersView
# in the urls.py of this django app (profiles)
@method_decorator(login_required, name='dispatch')
class UsersView(TemplateView):
    """
    Shows all the users and their addresses.
    """
    template_name = 'profiles/users_lst.html'

    def get_context_data(self, **kwargs):
        users = Users.objects.all()
        context = {'object_list': users}
        return context


@method_decorator(login_required, name='dispatch')
class UsersListView(ListView):
    """
    A class to list all the users.
    """
    model = Users
    template_name = 'profiles/users_lst.html'


@method_decorator(login_required, name='dispatch')
class UserDetailView(DetailView):
    """
    Show the user details.
    """
    model = Users
    template_name = 'profiles/details.html'


@method_decorator(login_required, name='dispatch')
class UsersCreateView(CreateView):
    """
    A view to create a new user.
    """
    model = Users
    template_name = 'profiles/new.html'
    success_url = reverse_lazy("profiles:new")

    form_class = UsersForm
    second_form_class = AddressForm

    def get_context_data(self, **kwargs):
        context = super(UsersCreateView, self).get_context_data(**kwargs)
        if 'users_form' not in context:
            context['users_form'] = self.form_class(self.request.GET)
        if 'address_form' not in context:
            context['address_form'] = self.second_form_class(self.request.GET)
        return context

    def post(self, request, **kwargs):
        self.object = self.get_object
        users_form = self.form_class(request.POST)
        address_form = self.second_form_class(request.POST)
        if users_form.is_valid() and address_form.is_valid():
            create_user = users_form.save(commit=False)
            create_user.address = address_form.save()
            create_user.save()
            return HttpResponseRedirect(self.get_success_url())
        else:
            return self.render_to_response(context={'users_form': users_form,
                                                    'address_form': address_form})

profiles/templates/details.html
{% extends 'base.html' %}

{% block title %}Details - {{ object }}{% endblock %}

{% block content %}
<div class="container">
    <h1>Details for user: {{ object }}</h1>

    <table class="table table-sm">
        <thead>
            <th>ID</th>
            <th>First Name</th>
            <th>Last Name</th>
            <th>Age</th>
            <th>Gender</th>
            <th>Email</th>
            <th>Address</th>
            <th>City</th>
            <th>State</th>
            <th>Country</th>
            <th>Zip Code</th>
            <th>Active</th>
            <th>Time Zone</th>
        </thead>
        <tbody>
        <tr>
            <td>{{ object.id }}</td>
            <td>{{ object.first_name }}</td>
            <td>{{ object.last_name }}</td>
            <td>
                {% if object.age %}
                {{ object.age }}
                {% endif %}
            </td>
            <td>
                {% if object.gender %}
                {{ object.gender }}
                {% endif %}
            </td>
            <td>{{ object.email }}</td>
            <td>{{ object.address }}</td>
            <td>
                {% if object.city %}
                {{ object.city }}
                {% endif %}
            </td>
            <td>
                {% if object.state %}
                {{ object.state }}
                {% endif %}
            </td>
            <td>
                {% if object.country %}
                {{ object.country }}
                {% endif %}
            </td>
            <td>
                {% if object.zip_code %}
                {{ object.zip_code }}
                {% endif %}
            </td>
            <td>{{ object.active }}</td>
            <td>
                {% if object.timezone %}
                {{ object.timezone }}
                {% endif %}
            </td>

        </tr>
        </tbody>
    </table>
</div>
<style>
    h1 {
    text-align: center;
    color: darkblue;
    }
</style>
{% endblock content %}

profiles/templates/index.html
{% extends 'base.html' %}

{% block title %}Users - Detailed List{% endblock %}

{% block content %}
<div class="container">
    <h1 class="title">Users</h1>
    <table class="table table-sm">
        <thead>
            <th>ID</th>
            <th>First Name</th>
            <th>Last Name</th>
            <th>Age</th>
            <th>Gender</th>
            <th>Email</th>
            <th>Address</th>
            <th>City</th>
            <th>State</th>
            <th>Country</th>
            <th>Zip Code</th>
            <th>Active</th>
            <th>Time Zone</th>
        </thead>
        <tbody>
        {% for user in users_lst %}
        <tr>
            <td>{{ user.id }}</td>
            <td>{{ user.first_name }}</td>
            <td>{{ user.last_name }}</td>
            <td>
                {% if user.age %}
                {{ user.age }}
                {% endif %}
            </td>
            <td>
                {% if user.gender %}
                {{ user.gender }}
                {% endif %}
            </td>
            <td>{{ user.email }}</td>
            <td>{{ user.address }}</td>
            <td>
                {% if user.city %}
                {{ user.city }}
                {% endif %}
            </td>
            <td>
                {% if user.state %}
                {{ user.state }}
                {% endif %}
            </td>
            <td>
                {% if user.country %}
                {{ user.country }}
                {% endif %}
            </td>
            <td>
                {% if user.zip_code %}
                {{ user.zip_code }}
                {% endif %}
            </td>
            <td>{{ user.active }}</td>
            <td>
                {% if user.timezone %}
                {{ user.timezone }}
                {% endif %}
            </td>

        </tr>
        {% endfor %}
        </tbody>
    </table>
</div>
<style>
    h1 {
    text-align: center;
    color: darkblue;
    }
</style>
{% endblock %}

profiles/templates/new.html
{% extends 'base.html' %}

{% block title %}Users - New{% endblock %}

{% block content %}

<div class="cont">
    <form method="POST" action="#">
    <h1>Add new user</h1>

        {% csrf_token %}
        {{ users_form.as_p }}
        {{ address_form.as_p }}

        <div class="row">
            <input type="submit" class="btn btn-primary col-md-4" value="Submit">
            <div class="col-md-4"></div>
            <input type="button" class="btn btn-danger col-md-4" value="Cancel" onclick=window.location.href="{% url 'profiles:simple_lst' %}";>
        </div>
    </form>
<style>
    input[type=text], input[type=number], textarea {
        width: 100%;
    }
    ul {
    display: inline;
    float: right;
    }
    h1 {
    color: darkblue;
    margin: auto;
    width: 100%;
    padding: 10px;
    text-align: center;
    }
    .cont {
    margin: auto;
    width: 50%;
    margin-bottom: 40px;
    }
    body {
    color: green;
    }

</style>
</div>

{% endblock %}

profiles/templates/profiles/details.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Details - {{ object }}{% endblock %}

{% block content %}
<div class="container">
    <h1 class="mt-3">Details for user: {{ object }}</h1>

    <table class="table table-sm mt-3">
        <thead>
            <th>ID</th>
            <th>First Name</th>
            <th>Last Name</th>
            <th>Age</th>
            <th>Gender</th>
            <th>Email</th>
            <th>Address</th>
            <th>City</th>
            <th>State</th>
            <th>Country</th>
            <th>Zip Code</th>
            <th>Active</th>
            <th>Time Zone</th>
        </thead>
        <tbody>
        <tr>
            <td>{{ object.id }}</td>
            <td>{{ object.first_name }}</td>
            <td>{{ object.last_name }}</td>
            <td>
                {% if object.age %}
                {{ object.age }}
                {% endif %}
            </td>
            <td>
                {% if object.gender %}
                {{ object.gender }}
                {% endif %}
            </td>
            <td>{{ object.email }}</td>
            <td>{{ object.address }}</td>
            <td>
                {% if object.city %}
                {{ object.city }}
                {% endif %}
            </td>
            <td>
                {% if object.state %}
                {{ object.state }}
                {% endif %}
            </td>
            <td>
                {% if object.country %}
                {{ object.country }}
                {% endif %}
            </td>
            <td>
                {% if object.zip_code %}
                {{ object.zip_code }}
                {% endif %}
            </td>
            <td>{{ object.active }}</td>
            <td>
                {% if object.timezone %}
                {{ object.timezone }}
                {% endif %}
            </td>

        </tr>
        </tbody>
    </table>
</div>

<link rel="stylesheet" href="{% static 'profiles/css/details.css' %}">

{% endblock content %}

profiles/templates/profiles/index-delete.html
{% extends 'base.html' %}

{% block title %}Users - Detailed List{% endblock %}

{% block content %}
<div class="container">
    <h1 class="title">Users</h1>
    <table class="table table-sm">
        <thead>
            <th>ID</th>
            <th>First Name</th>
            <th>Last Name</th>
            <th>Age</th>
            <th>Gender</th>
            <th>Email</th>
            <th>Address</th>
            <th>City</th>
            <th>State</th>
            <th>Country</th>
            <th>Zip Code</th>
            <th>Active</th>
            <th>Time Zone</th>
        </thead>
        <tbody>
        {% for user in users_lst %}
        <tr>
            <td>{{ user.id }}</td>
            <td>{{ user.first_name }}</td>
            <td>{{ user.last_name }}</td>
            <td>
                {% if user.age %}
                {{ user.age }}
                {% endif %}
            </td>
            <td>
                {% if user.gender %}
                {{ user.gender }}
                {% endif %}
            </td>
            <td>{{ user.email }}</td>
            <td>{{ user.address }}</td>
            <td>
                {% if user.city %}
                {{ user.city }}
                {% endif %}
            </td>
            <td>
                {% if user.state %}
                {{ user.state }}
                {% endif %}
            </td>
            <td>
                {% if user.country %}
                {{ user.country }}
                {% endif %}
            </td>
            <td>
                {% if user.zip_code %}
                {{ user.zip_code }}
                {% endif %}
            </td>
            <td>{{ user.active }}</td>
            <td>
                {% if user.timezone %}
                {{ user.timezone }}
                {% endif %}
            </td>

        </tr>
        {% endfor %}
        </tbody>
    </table>
</div>
<style>
    h1 {
    text-align: center;
    color: darkblue;
    }
</style>
{% endblock %}

profiles/templates/profiles/new.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Users - New{% endblock %}

{% block content %}

<div class="cont">
    <form method="POST" action="">
    <h1 class="mt-3">Add new user</h1>

        {% csrf_token %}
        {{ users_form.as_p }}
        {{ address_form.as_p }}

        <div class="row">
            <input type="submit" class="btn btn-primary col-md-4" value="Submit">
            <div class="col-md-4"></div>
            <input type="button" class="btn btn-danger col-md-4" value="Cancel" onclick=window.location.href="{% url 'profiles:simple_lst' %}";>
        </div>
    </form>

</div>

<link rel="stylesheet" href="{% static 'profiles/css/new.css' %}">

{% endblock %}

profiles/templates/profiles/users.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Users - Detailed List{% endblock %}

{% block content %}
<div class="container">
    <h1 class="title mt-3">Users</h1>
    <table class="table table-sm mt-3">
        <thead>
            <th>ID</th>
            <th>First Name</th>
            <th>Last Name</th>
            <th>Age</th>
            <th>Gender</th>
            <th>Email</th>
            <th>Address</th>
            <th>City</th>
            <th>State</th>
            <th>Country</th>
            <th>Zip Code</th>
            <th>Active</th>
            <th>Time Zone</th>
        </thead>
        <tbody>
        {% for user in users_lst %}
        <tr>
            <td>{{ user.id }}</td>
            <td>{{ user.first_name }}</td>
            <td>{{ user.last_name }}</td>
            <td>
                {% if user.age %}
                {{ user.age }}
                {% endif %}
            </td>
            <td>
                {% if user.gender %}
                {{ user.gender }}
                {% endif %}
            </td>
            <td>{{ user.email }}</td>
            <td>{{ user.address }}</td>
            <td>
                {% if user.city %}
                {{ user.city }}
                {% endif %}
            </td>
            <td>
                {% if user.state %}
                {{ user.state }}
                {% endif %}
            </td>
            <td>
                {% if user.country %}
                {{ user.country }}
                {% endif %}
            </td>
            <td>
                {% if user.zip_code %}
                {{ user.zip_code }}
                {% endif %}
            </td>
            <td>{{ user.active }}</td>
            <td>
                {% if user.timezone %}
                {{ user.timezone }}
                {% endif %}
            </td>

        </tr>
        {% endfor %}
        </tbody>
    </table>
</div>

<link rel="stylesheet" href="{% static 'profiles/css/users.css' %}">

{% endblock %}

profiles/templates/profiles/users_lst.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Users - Simple List{% endblock %}

{% block content %}

<div class="container">

    <div>
        <h1 class="mt-3">Users</h1>
    </div>

<table class="table mt-3">
    <thead>
        <th>User</th>
        <th>Address</th>
        <th>Options</th>
    </thead>

    {% if object_list %}
{% for user in object_list %}

    <tbody>
        <tr>
            <td>{{ user }}</td>
            <td>{{ user.address }}</td>
            <td><a href="{% url 'profiles:user_detail' user.id%}">See Details</a></td>
        </tr>
    </tbody>

{% endfor %}
    {% endif %}
</table>

</div>

<link rel="stylesheet" href="{% static 'profiles/css/users_lst.css' %}">

{% endblock %}

profiles/templates/users_lst.html
{% extends 'base.html' %}

{% block title %}Users - Simple List{% endblock %}

{% block content %}

<div class="container">

    <div>
        <h1>Users</h1>
    </div>

<table class="table">
    <thead>
        <th>User</th>
        <th>Address</th>
    </thead>

    {% if object_list %}
{% for user in object_list %}

    <tbody>
        <tr>
            <td>{{ user }}</td>
            <td>{{ user.address }}</td>
            <td><a href="{% url 'profiles:user_detail' user.id%}">See Details</a></td>
        </tr>
    </tbody>

{% endfor %}
    {% endif %}
</table>

</div>
<style>
    h1 {
    text-align: center;
    color: darkblue;
    }
    a:hover {
    text-decoration: none;}
</style>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{%endblock%}</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
</head>
<body>

{% block header %}
<navbar>
    <div class="container-fluid mt-3">
            <a href="{% url 'home' %}">Home</a>
        {% if user.is_authenticated %} /
            <a href="{% url 'profiles:simple_lst' %}">Simple List</a> /
            <a href="{% url 'profiles:full_list' %}">Detailed List</a> /
            <a href="{% url 'profiles:new' %}">Add New User</a> /
            <a href="{% url 'logout' %}">Log out</a>
        {% else %} /
            <a href="{% url 'login' %}">Login</a>
        {% endif %}
    </div>
</navbar>

{% endblock %}

{% block content %}

{% endblock content %}

</body>
</html>

templates/home.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Home - Users{% endblock %}

{% block content %}

<div class="container">
    <h1 class="mt-3">User Registration Home Page</h1>
    <ul>
        <li><a href="{% url 'profiles:simple_lst' %}">Simple List</a></li>
        <li><a href="{% url 'profiles:full_list' %}">Detailed List</a></li>
        <li><a href="{% url 'profiles:new' %}">Add New User</a></li>
    </ul>
</div>

<link rel="stylesheet" href="{% static 'profiles/css/home.css' %}">

{% endblock %}

templates/register.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Register{% endblock %}

{% block content %}

<div class="container">
    {% if user.is_authenticated %}
    <h1 class="mt-3">You are logged in as <br>'{{ user.username }}'</h1>
    {% else %}
    <h1 class="mt-3">Register</h1>
    <form action="" method="post" class="form">

        {% csrf_token %}

        {{ form.as_p }}

        <input type="submit" value="Register">
    </form>
    {% endif %}

</div>

<link rel="stylesheet" href="{% static 'registration/css/register.css' %}">

{% endblock %}